feat: check path of save reports

diff --git a/.github/workflows/lighthouseci.yaml b/.github/workflows/lighthouseci.yaml
--- a/.github/workflows/lighthouseci.yaml
+++ b/.github/workflows/lighthouseci.yaml
@@ -44,6 +44,9 @@ jobs:
       - name: Run Lighthouse CI
         run: npm run lhci -- --ci
 
+      - name: List LighthouseCI output
+        run: ls -la .lighthouseci || echo "Directory not found"
+
       - name: Upload Lighthouse Report
         uses: actions/upload-artifact@v4
         with:
